---
title: "statistics_session3"
author: "liyouyou"
date: "2023-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sampling)
library(patchwork) # 将图组合在一起
library(skimr)
load("/Users/liyou/class/r-learning/data/lj_sh_2019.RData")
theme_set(theme(text = element_text(family = "Songti SC")))
```

## 变量、随机变量
```{r}

```

## 变量的分布
```{r}

```


## 随机抽样
1. 简单随机抽样
```{r}
lj_sample <- slice_sample(lj, n = 100)
skimr::skim(lj_sample)

lj_sample <- slice_sample(lj, prop = 0.1)

(p1 <- lj %>% 
  ggplot(aes(price_sqm)) +
  geom_histogram())

(p2 <- lj_sample %>% 
  ggplot(aes(price_sqm)) +
  geom_histogram())
p1 + p2
# p1 / p2

```
2. strata sampling 分层抽样
```{r}
lj_sample_3 <- lj %>% 
  group_by(line) %>% 
  slice_sample(prop = 0.1) %>% 
  ungroup()
table(lj_sample_3$line)
(p3 <- lj_sample_3 %>% 
  ggplot(aes(price_sqm)) +
  geom_histogram())

p1 + p2 + p3
```
3. cluster sampling 整群抽样
```{r}
cluster(lj, c("line"), size = 10)
```

## 中心极限定理
```{r}
# 原始分布
mean(lj$price_sqm)

s1 <- slice_sample(lj, n = 100)
mean(s1$price_sqm)

v <- vector()
for (i in 1:100) {
  s <- slice_sample(lj, n = 100)
  v[i] <- mean(s$price_sqm)
}
mean(v)
var(v) * 100
var(lj$price_sqm)

hist(v)

```
```{r}
(s_step <- seq(5,50, by=5))
```

```{r}
## CLT
### simulation of clt with R

set.seed(12)
x <- vector()
# 满足卡方分布
y <- rchisq(10000,1)

s_step <- seq(5,50, by=5)
par(mfrow=c(5,2))

# for (i in 1:100) {
#   sample_y <- sample(y,30)
#   x[i] <- mean(sample_y)
# }

par(mar=c(0.1,0.1,0.1,0.1))
for (s_size in s_step) {
    
  for (i in 1:100) {
      sample_y <- sample(y,s_size)
      x[i] <- mean(sample_y)
    
  }
  
  hist(x,main = paste0("n = ", s_size),freq = FALSE)
  a <- seq(-100,100,by=1)
  b <- dnorm(a,mean = mean(x),sd = sd(x))
  #curve(a,b,col="blue")
}

par(mfrow= c(1,1)) # restore the parameter
### simulation of clt with R--------------------end
```

## 正态分布
```{r}
#rnorm()
#pnorm() 分位数，计算概率，左边
#qnorm() 计算概率对应的点
#dnorm() TODO 需要查下资料
# 68.26%
pnorm(1) - pnorm(-1)
# 95.44%
pnorm(2) - pnorm(-2)
# 99.73%
pnorm(3) - pnorm(-3)

# 问题1 z小于等于1.00的概率是多少？
pnorm(1, lower.tail = T)
# 问题2
pnorm(1.25, lower.tail = T) - pnorm(-0.50)
# 问题3
pnorm(1.58, lower.tail = F)
# 问题4
qnorm(0.1, lower.tail = F)
qnorm(0.9)

# z 0.01
qnorm(0.99)
# z 0.025
qnorm(0.975)
# z 0.05
qnorm(0.95)
# z 0.005
qnorm(0.995)

1 - pnorm(1.28)

```
## 认识正态分布
```{r}
a <- rnorm(1000)
ggplot(data.frame(x = a), aes(x)) +
  geom_histogram(binwidth = 0.25) +
  #stat_function(fun = ~ dnorm(.x) * 0.25 * 1000, color = "red", n = 100) +
  stat_function(fun = ~ dnorm(.x) * 0.25 * 1000, args = list(mean = 1,sd = 1) ,color = "blue", n = 100)

```
## 机油题目
```{r}
# 问题1
# 非标准
1 - pnorm(20, 15, 6)
# 标准
1 - pnorm(5/6)
# 问题2
qnorm(0.95, 15, 6)
```

## 卡方分布
```{r}
a <- rchisq(1000, 15)
ggplot(data.frame(x = a), aes(x)) +
  geom_histogram(binwidth = 0.25) +
  stat_function(fun = ~dchisq(.x, 15) * 0.25 * 1000, color = "red")

#rchisq()
#pchisq()
#qchisq()

```
## T分布
```{r}
ggplot(data.frame(x = rt(1000, 10)), aes(x)) +
  geom_histogram(binwidth = 0.25) +
  stat_function(fun = ~dt(.x, 10) * 0.25 * 1000, color = "red") +
  stat_function(fun = ~dnorm(.x) * 0.25 * 1000, color = "green")
qt(0.975, 100)
# qt(0.975, seq(100, 1000, 10))
```
## F分布
```{r}
#rf()
#pf()
#qf()
#df()
```

## 练习
```{r}
s1 <- lj %>% 
  group_by(line) %>% 
  slice_sample(prop = 0.1) %>% 
  ungroup()
#nrow(s1)
mean(lj$price_sqm)
sd(lj$price_sqm)
# 作为点估计值
mean(s1$price_sqm)
sd(s1$price_sqm)

# 95% interval estimation 误差限
(E1 <- qnorm(0.975) * sd(s1$price_sqm) / sqrt(nrow(s1)))
mean(s1$price_sqm) + c(-E1, E1)
# 用T分布代替正态分布，用样本方差代替总体方差
(E2 <- qt(0.975, 641) * sd(s1$price_sqm) / sqrt(nrow(s1)))
mean(s1$price_sqm) + c(-E1, E1)
# 方便计算置信区间
t.test(s1$price_sqm)

```


