---
title: "statistics_session_10-21"
author: "liyouyou"
date: "2023-10-21"
output: html_document
---

```{r setup, include = FALSE,echo = FALSE}
knitr::opts_chunk$set(echo = FALSE,error = FALSE, warning = FALSE, message = FALSE,
                      out.width = "100%", split = FALSE, fig.align = "center")
library(tidyverse)
library(showtext)
library(gridExtra)
library(sampling)

showtext_auto(enable = TRUE)
#theme_set(theme(text = element_text(family = "Songti SC")))

```


```{r }
# 合格率 6xigema  3.4/百万      有1.5倍的偏移量 6 + 1.5， -6 + 1.5 所以是 7.5 和 -4.5
1 - (pnorm(7.5) - pnorm(-4.5))
```

```{r}
####################################
#
# Simulation of CLT
#
####################################
set.seed(123)

x <- runif(10000,0,100)

mean_x <- mean(x)
sd_x <- sd(x)

# sample x with sample size 30
x_sample <- sample(x,30)

# sample mean
x_bar <- mean(x_sample)

# margin of error
E <- qnorm(0.975)*sd_x/sqrt(30)

x_bar+c(-E,E)


# simulation with ggplot --------------------------------------------------
library(tidyverse)
library(gridExtra)

meanset <- rnorm(50,50000,1000)
meanset <- as.data.frame(meanset)
colnames(meanset) <- "Mean"

# Creating Interval Boundaries Varying by Confidence Level
# add liyou   1677 是qt(0.95, 49) * 1000
meanset90 <- meanset %>% mutate(upper = Mean + 1677) %>% mutate(lower = Mean - 1677)
meanset95 <- meanset %>% mutate(upper = Mean + 2010) %>% mutate(lower = Mean - 2010)
meanset99 <- meanset %>% mutate(upper = Mean + 2680) %>% mutate(lower = Mean - 2680)

Sample <- seq(1,50,1)
Sample <- as.data.frame(Sample)

ci90 <- cbind(Sample, meanset90)
ci95 <- cbind(Sample, meanset95)
ci99 <- cbind(Sample, meanset99)

#Determining Whether a Confidence Interval Captures the True Parameter Value
ci95 <- ci95 %>% mutate(Capture = ifelse(lower < 50000, ifelse(upper > 50000, 1, 0), 0))
ci90 <- ci90 %>% mutate(Capture = ifelse(lower < 50000, ifelse(upper > 50000, 1, 0), 0))
ci99 <- ci99 %>% mutate(Capture = ifelse(lower < 50000, ifelse(upper > 50000, 1, 0), 0))
ci90$Capture <- factor(ci90$Capture, levels = c(0,1))
ci95$Capture <- factor(ci95$Capture, levels = c(0,1))
ci99$Capture <- factor(ci99$Capture, levels = c(0,1))

head(ci90)

# Generating Confidence Interval Plots in a Grid (with Varying Confidence Levels)
colorset = c('0'='red','1'='black')

ci_plot_90 <- ci90 %>% 
  ggplot(aes(x = Sample, y = Mean)) + 
  geom_point(aes(color = Capture)) + 
  geom_errorbar(aes(ymin = lower, ymax = upper, color = Capture)) + 
  scale_color_manual(values = colorset) + 
  coord_flip() + 
  geom_hline(yintercept = 50000, linetype = "dashed", color = "blue") + 
  labs(title = "90% Confidence Intervals") + 
  theme(plot.title = element_text(hjust = 0.5)) + ylim(40000,60000)

ci_plot_95 <- ci95 %>% 
  ggplot(aes(x = Sample, y = Mean)) + 
  geom_point(aes(color = Capture)) + 
  geom_errorbar(aes(ymin = lower, ymax = upper, color = Capture)) + 
  scale_color_manual(values = colorset) + 
  coord_flip() + 
  geom_hline(yintercept = 50000, linetype = "dashed", color = "blue") + 
  labs(title = "95% Confidence Intervals") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  ylim(40000,60000)

ci_plot_99 <- ci99 %>% 
  ggplot(aes(x = Sample, y = Mean)) + 
  geom_point(aes(color = Capture)) + 
  geom_errorbar(aes(ymin = lower, ymax = upper, color = Capture)) + 
  scale_color_manual(values = colorset) + 
  coord_flip() + 
  geom_hline(yintercept = 50000, linetype = "dashed", color = "blue") + 
  labs(title = "99% Confidence Intervals") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  ylim(40000,60000)

grid.arrange(ci_plot_90, ci_plot_95, ci_plot_99, ncol = 3)

#Simulating Confidence Intervals for Different Sample Sizes

meanset_9 <- rnorm(50,50000,1333)
meanset_9 <- as.data.frame(meanset_9)
colnames(meanset_9) <- "Mean"
meanset_25 <- rnorm(50,50000,1000)
meanset_25 <- as.data.frame(meanset_25)
colnames(meanset_25) <- "Mean"
meanset_100 <- rnorm(50,50000,500)
meanset_100 <- as.data.frame(meanset_100)
colnames(meanset_100) <- "Mean"

meanset_9 <- meanset_9 %>% mutate(upper = Mean + 3075) %>% mutate(lower = Mean - 3075)
meanset_25 <- meanset_25 %>% mutate(upper = Mean + 2064) %>% mutate(lower = Mean - 2064)
meanset_100 <- meanset_100 %>% mutate(upper = Mean + 992) %>% mutate(lower = Mean - 992)

Sample <- seq(1,50,1)
Sample <- as.data.frame(Sample)

n9 <- cbind(Sample, meanset_9)
n25 <- cbind(Sample, meanset_25)
n100 <- cbind(Sample, meanset_100)

n9 <- n9 %>% mutate(Capture = ifelse(lower < 50000, ifelse(upper > 50000, 1, 0), 0))
n25 <- n25 %>% mutate(Capture = ifelse(lower < 50000, ifelse(upper > 50000, 1, 0), 0))
n100 <- n100 %>% mutate(Capture = ifelse(lower < 50000, ifelse(upper > 50000, 1, 0), 0))
n9$Capture <- factor(n9$Capture, levels=c(0,1))
n25$Capture <- factor(n25$Capture, levels=c(0,1))
n100$Capture <- factor(n100$Capture, levels=c(0,1))

head(n25)

# Generating Confidence Interval Plots in a Grid (with Varying Sample Sizes)
colorset = c('0'='red','1'='black')

n_plot_9 <- n9 %>% ggplot(aes(x = Sample, y = Mean)) + geom_point(aes(color = Capture)) + geom_errorbar(aes(ymin = lower, ymax = upper, color = Capture)) + scale_color_manual(values = colorset) + coord_flip() + geom_hline(yintercept = 50000, linetype = "dashed", color = "blue") + labs(title = "Confidence Intervals, n = 9") + theme(plot.title = element_text(hjust = 0.5)) + ylim(40000,60000)

n_plot_25 <- n25 %>% ggplot(aes(x = Sample, y = Mean)) + geom_point(aes(color = Capture)) + geom_errorbar(aes(ymin = lower, ymax = upper, color = Capture)) + scale_color_manual(values = colorset) + coord_flip() + geom_hline(yintercept = 50000, linetype = "dashed", color = "blue") + labs(title = "Confidence Intervals, n = 25") + theme(plot.title = element_text(hjust = 0.5)) + ylim(40000,60000)

n_plot_100 <- n100 %>% ggplot(aes(x = Sample, y = Mean)) + geom_point(aes(color = Capture)) + geom_errorbar(aes(ymin = lower, ymax = upper, color = Capture)) + scale_color_manual(values = colorset) + coord_flip() + geom_hline(yintercept = 50000, linetype = "dashed", color = "blue") + labs(title = "Confidence Intervals, n = 100") + theme(plot.title = element_text(hjust = 0.5)) + ylim(40000,60000)

grid.arrange(n_plot_9, n_plot_25, n_plot_100, ncol = 3)
```

## 区间估计
```{r}
lj <- read_csv("../data/2023-09-12_cleaned.csv")
mean(lj$price_sqm)
var(lj$price_sqm)
sd(lj$price_sqm)

# 1. 抽样，根据抽样来做区间估计
set.seed(1234)
lj_s <- sample_n(lj, 100)
sample_mean <- mean(lj_s$price_sqm)
# 1.1 假定方差已知  误差限
(E <- qnorm(0.975) * sd(lj$price_sqm) / sqrt(100))
(ci_1 <- sample_mean + c(-E, E))
# 1.2 假定方差未知
(E2 <- qt(0.975, 99) * sd(lj_s$price_sqm) / sqrt(100))
(ci_2 <- sample_mean + c(-E2, E2))
```


```{r}
# 居民收入水平评估
# n = 36,样本平均值 31100，假设总体标准差为 4500，计算95%
# 31100 +- （1.96 * 4500 / sqrt(36)     29630 , 32570 

# 如果 95%的置信度，误差限不超过500 多大容量？
# 1.96^2 * 4500^2 / 500^2   312  向上取整


# 比例估计
# 调查支持程度，调查500人 220人支持， 95%置信，总体范围
# pba = 0.44 +- 1.96 sqrt (0.44 * 0.56 / 500)  39.65% 48.35% 之间

# 方差预估
# 减少到站时间方差，24次到站，总体95%以内
bustime <- read_csv("../data/BusTimes.csv")
bustime <- bustime %>% 
  select(Times)

bus_var <- var(bustime$Times, na.rm = T)
(24 - 1) * bus_var / qchisq(0.975, 23)
(24 - 1) * bus_var / qchisq(0.025, 23)
```

```{r}
lj <- lj %>% 
  mutate(across(is.character, as.factor))
# 多使用 purr里面的 map_*  替换 apply*
```


# 假设检验
```{r}
# 题目：急救中心表示12分钟，抽样40次 13.25  sd 为 3.2 ,显著性水平 0.05

# 1. 提出原假设和备选假设  H0: mu <= 12   Ha: mu > 12

# 2. 给定显著性水平 alpha = 0.05

# 3. 计算 z = (13.25 - 12) / (3.2 / sqrt(40)) = 2.47  这是转换成标准正态分布

# 4. 临界值 z0.05 = 1.644 < 2.47         z0.05 = qnorm(0.95)

# 5. 拒绝原假设

#第二种
# 1. 提出原假设 H0: mu >= 12  Ha:mu < 12

# 2. alpha = 0.05

# 3. z = (13.25 - 12)/(3.2/sqrt(40)) = 2.47

# 4. -z = -1.644 因为z > -zalpha

# 5. 不拒绝原假设

# 将题目换成12.5分钟 z 如下，落在 1.644 左侧，大概率事件，不拒绝原假设
# H0: mu >= 12  Ha: mu < 12
0.5 / (3.2 / sqrt(40))
# beta 错误大小,首先要给一个一定为假的区域，比如 11.9， 犯第二类错误的大小为 95%
1 - pnorm(12-1.645*3.2/sqrt(40), 11.9, 3.2/sqrt(40))
# 随着逐步的靠近，犯第二类错误的可能性会越来越大    检验能力曲线
1 - pnorm(12-1.645*3.2/sqrt(40), seq(10,12,0.1), 3.2/sqrt(40))
```

```{r}
# 例题： 
# H0: mu <= 25  Ha: mu > 25   n = 40, mean 26.4  sd 6
# a: 计算 test statistic z = (26.4 - 25) / (6/sqrt(40))  =  1.47
(26.4 - 25) / (6/sqrt(40))
```
```{r}
# b: 计算p-value = 0.07
1 - pnorm(26.4, 25, 6/sqrt(40))
```
```{r}
# c: 在显著性水平 0.01下， 0.07 > 0.01 不拒绝原假设
# d: z > z0.01=2.326，实际上z < z0.01   不拒绝
```


## 双侧检验
```{r}
# 牙膏题目：H0: mu = 6  Ha: mu <> 6 ,要求显著性水平 0.03 
# z = (6.1 -6)/(0.2/sqrt(30) = 2.74
(6.1 -6)/(0.2/sqrt(30))
# p-value = (1 - pnorm(2.74)) * 2 = 0.006
(1 - pnorm(2.74)) * 2
# 0.006 < 0.03 拒绝原假设
```

## 两个总体

```{r}
# 检验靠近地铁和不靠近地铁的二手房 均价是否有显著差异
lj <- read_csv("../data/2023-09-12_cleaned.csv")
lj <- lj %>% 
  mutate(near_subway = ifelse(near_subway == "近地铁", 1, 0))
lj <- lj %>% 
  mutate(near_subway = ifelse(is.na(near_subway), 0, 1))
lj <- lj %>% 
  mutate(near_subway = 
           as.factor(near_subway))

t.test(lj$price_sqm ~ lj$near_subway)

# 比例检验
prop.test(table(lj$near_subway))
```






