---
title: "Statistics_Session2"
author: "李游游"
date: "2023-09-23"
output:
  html_document: default
  # pdf_document: default
---

```{r setup, include=FALSE}
# need install
#install.packages("devtools")
#install.packages("rstatix")
#install.packages("jiebaR")

library(tidyverse)
library(e1071)
library(jiebaR)
library(wordcloud2)
library(rstatix)
load("/Users/liyou/class/r-learning/data/lj_sh_2019.RData")
# library(showtext)
knitr::opts_chunk$set(echo = TRUE)
theme_set(theme(text = element_text(family = "Songti SC")))
```

# 三类指标
## 集中趋势
* mean 均值
* median 中位数
* mode 众数
* quartile 四分位数
* percentile 百分位数

```{r}
# 均值
mean(lj$price_sqm)
# 中位数
median(lj$price_sqm)
# 众数
get_mode(lj$decoration)
get_mode(lj$line)
# 四分位数
quantile(lj$price_sqm, 0.25)
quantile(lj$price_sqm, 0.75)
quantile(lj$price_ttl,0.75) - quantile(lj$price_ttl,0.25)
# 百分位数
quantile(lj$price_ttl,seq(0,1,0.01))
```


## 离散趋势
* range 范围、区域
* IQR 内距、四分位差
* variance 方差
* s.d. 标准差
* s.d./x拔 离散系数

## 形状
* skewness   偏度
* kurtosis   峰度

## 其他工具
```{r }
# segment(lj$property_name,worker())  输出太多
wordcloud2(freq(segment(lj$property_name,worker())))
```


# 五种基本类型
## 分类型数据

1. Bar graph (条形图)
```{r}
lj %>% 
  ggplot(aes(line)) + 
  geom_bar()
  # theme(axis.title.x = element_text(angle = 2))
  
```
## 数值型数据
1. 直方图
```{r}
lj %>% 
  ggplot(aes(price_ttl)) +
  geom_histogram(color = "green") 
  #scale_x_continuous(limits = c(65, 1000))
```
2. 散点图

```{r}
lj %>% 
  ggplot(aes(building_area, price_ttl, color = line)) +
  geom_point() +
  geom_smooth(method = "lm", se = F)
```

3. boxplot 箱线图
```{r}
set.seed(1234)
a <- data.frame(x=rnorm(100,10,2))
ggplot(a, aes(x)) + 
  geom_boxplot() +
  # 中位数
  geom_vline(xintercept = median(a$x), color = "red") +
  # 25%分位数
  geom_vline(xintercept = quantile(a$x, 0.25), color = "green") +
  # 75%分位数
  geom_vline(xintercept = quantile(a$x, 0.75), color = "blue") +
  # Q3 + 1.5IQR 离群点
  geom_vline(xintercept = quantile(a$x, 0.75) + 1.5*IQR(a$x), color = "blue") +
  # Q1 - 1.5IQR 离群点
  geom_vline(xintercept = quantile(a$x, 0.25) - 1.5*IQR(a$x), color = "yellow") +
  # 正常最小值点
  geom_vline(xintercept = min(a$x), color = "blue")

lj %>% 
  ggplot(aes(price_sqm, color = line)) + 
  geom_boxplot() + 
  coord_flip()
```

5. line graph
```{r}
temp <- lj %>% 
  count(building_year)
temp %>% 
  ggplot(aes(building_year,n)) + 
  geom_line() +
  scale_x_discrete(breaks = seq(1911, 2019, 1))
```


公式表示法
$$
\bar X N(\mu,\sigma^2)
$$
## 下节课预习

* rnorm(100, 0, 1) # 100个均值为0 标准差为1的随机数
* pnorm() # 算概率
* qnorm()
* dnorm() 




